### PR TITLE
Fix #24: Update code for Julia v0.6

### LINKED ISSUE #24: Update of code is needed
Simply running

``` julia
using GeometricalPredicates
```

gives

``` julia

WARNING: deprecated syntax "abstract AbstractPoint" at /Users/Azamat/.julia/v0.6/GeometricalPredicates/src/GeometricalPredicates.jl:63.
Use "abstract type AbstractPoint end" instead.

WARNING: deprecated syntax "abstract AbstractPoint2D<:AbstractPoint" at /Users/Azamat/.julia/v0.6/GeometricalPredicates/src/GeometricalPredicates.jl:64.
Use "abstract type AbstractPoint2D<:AbstractPoint end" instead.

WARNING: deprecated syntax "abstract AbstractPoint3D<:AbstractPoint" at /Users/Azamat/.julia/v0.6/GeometricalPredicates/src/GeometricalPredicates.jl:65.
Use "abstract type AbstractPoint3D<:AbstractPoint end" instead.

WARNING: deprecated syntax "abstract AbstractLine2D" at /Users/Azamat/.julia/v0.6/GeometricalPredicates/src/GeometricalPredicates.jl:67.
Use "abstract type AbstractLine2D end" instead.

WARNING: deprecated syntax "abstract AbstractPolygon2D" at /Users/Azamat/.julia/v0.6/GeometricalPredicates/src/GeometricalPredicates.jl:68.
Use "abstract type AbstractPolygon2D end" instead.

WARNING: deprecated syntax "abstract AbstractPrimitive" at /Users/Azamat/.julia/v0.6/GeometricalPredicates/src/GeometricalPredicates.jl:70.
Use "abstract type AbstractPrimitive end" instead.

WARNING: deprecated syntax "abstract AbstractUnOrientedPrimitive<:AbstractPrimitive" at /Users/Azamat/.julia/v0.6/GeometricalPredicates/src/GeometricalPredicates.jl:71.
Use "abstract type AbstractUnOrientedPrimitive<:AbstractPrimitive end" instead.

WARNING: deprecated syntax "abstract AbstractOrientedPrimitive<:AbstractPrimitive" at /Users/Azamat/.julia/v0.6/GeometricalPredicates/src/GeometricalPredicates.jl:72.
Use "abstract type AbstractOrientedPrimitive<:AbstractPrimitive end" instead.

WARNING: deprecated syntax "abstract AbstractPositivelyOrientedPrimitive<:AbstractOrientedPrimitive" at /Users/Azamat/.julia/v0.6/GeometricalPredicates/src/GeometricalPredicates.jl:73.
Use "abstract type AbstractPositivelyOrientedPrimitive<:AbstractOrientedPrimitive end" instead.

WARNING: deprecated syntax "abstract AbstractNegativelyOrientedPrimitive<:AbstractOrientedPrimitive" at /Users/Azamat/.julia/v0.6/GeometricalPredicates/src/GeometricalPredicates.jl:74.
Use "abstract type AbstractNegativelyOrientedPrimitive<:AbstractOrientedPrimitive end" instead.

WARNING: deprecated syntax "abstract AbstractTriangleUnOriented<:AbstractUnOrientedPrimitive" at /Users/Azamat/.julia/v0.6/GeometricalPredicates/src/GeometricalPredicates.jl:76.
Use "abstract type AbstractTriangleUnOriented<:AbstractUnOrientedPrimitive end" instead.

WARNING: deprecated syntax "abstract AbstractTetrahedronUnOriented<:AbstractUnOrientedPrimitive" at /Users/Azamat/.julia/v0.6/GeometricalPredicates/src/GeometricalPredicates.jl:77.
Use "abstract type AbstractTetrahedronUnOriented<:AbstractUnOrientedPrimitive end" instead.

WARNING: deprecated syntax "abstract AbstractPositivelyOrientedTriangle<:AbstractPositivelyOrientedPrimitive" at /Users/Azamat/.julia/v0.6/GeometricalPredicates/src/GeometricalPredicates.jl:78.
Use "abstract type AbstractPositivelyOrientedTriangle<:AbstractPositivelyOrientedPrimitive end" instead.

WARNING: deprecated syntax "abstract AbstractNegativelyOrientedTriangle<:AbstractNegativelyOrientedPrimitive" at /Users/Azamat/.julia/v0.6/GeometricalPredicates/src/GeometricalPredicates.jl:79.
Use "abstract type AbstractNegativelyOrientedTriangle<:AbstractNegativelyOrientedPrimitive end" instead.

WARNING: deprecated syntax "abstract AbstractPositivelyOrientedTetrahedron<:AbstractPositivelyOrientedPrimitive" at /Users/Azamat/.julia/v0.6/GeometricalPredicates/src/GeometricalPredicates.jl:80.
Use "abstract type AbstractPositivelyOrientedTetrahedron<:AbstractPositivelyOrientedPrimitive end" instead.

WARNING: deprecated syntax "abstract AbstractNegativelyOrientedTetrahedron<:AbstractNegativelyOrientedPrimitive" at /Users/Azamat/.julia/v0.6/GeometricalPredicates/src/GeometricalPredicates.jl:81.
Use "abstract type AbstractNegativelyOrientedTetrahedron<:AbstractNegativelyOrientedPrimitive end" instead.

WARNING: deprecated syntax "typealias TriangleTypes Union{AbstractTriangleUnOriented,AbstractPositivelyOrientedTriangle,AbstractNegativelyOrientedTriangle}" at /Users/Azamat/.julia/v0.6/GeometricalPredicates/src/GeometricalPredicates.jl:83.
Use "const TriangleTypes = Union{AbstractTriangleUnOriented,AbstractPositivelyOrientedTriangle,AbstractNegativelyOrientedTriangle}" instead.

WARNING: deprecated syntax "typealias TetrahedronTypes Union{AbstractTetrahedronUnOriented,AbstractPositivelyOrientedTetrahedron,AbstractNegativelyOrientedTetrahedron}" at /Users/Azamat/.julia/v0.6/GeometricalPredicates/src/GeometricalPredicates.jl:84.
Use "const TetrahedronTypes = Union{AbstractTetrahedronUnOriented,AbstractPositivelyOrientedTetrahedron,AbstractNegativelyOrientedTetrahedron}" instead.

WARNING: deprecated syntax "abstract AbstractOrientation" at /Users/Azamat/.julia/v0.6/GeometricalPredicates/src/GeometricalPredicates.jl:224.
Use "abstract type AbstractOrientation end" instead.

WARNING: deprecated syntax "abstract AbstractCoordinate" at /Users/Azamat/.julia/v0.6/GeometricalPredicates/src/GeometricalPredicates.jl:1053.
Use "abstract type AbstractCoordinate end" instead.

WARNING: deprecated syntax "abstract AbstractDirection" at /Users/Azamat/.julia/v0.6/GeometricalPredicates/src/GeometricalPredicates.jl:1069.
Use "abstract type AbstractDirection end" instead.
INFO: Precompiling module GeometricalPredicates.

WARNING: deprecated syntax "abstract AbstractPoint" at /Users/Azamat/.julia/v0.6/GeometricalPredicates/src/GeometricalPredicates.jl:63.
Use "abstract type AbstractPoint end" instead.

WARNING: deprecated syntax "abstract AbstractPoint2D<:AbstractPoint" at /Users/Azamat/.julia/v0.6/GeometricalPredicates/src/GeometricalPredicates.jl:64.
Use "abstract type AbstractPoint2D<:AbstractPoint end" instead.

WARNING: deprecated syntax "abstract AbstractPoint3D<:AbstractPoint" at /Users/Azamat/.julia/v0.6/GeometricalPredicates/src/GeometricalPredicates.jl:65.
Use "abstract type AbstractPoint3D<:AbstractPoint end" instead.

WARNING: deprecated syntax "abstract AbstractLine2D" at /Users/Azamat/.julia/v0.6/GeometricalPredicates/src/GeometricalPredicates.jl:67.
Use "abstract type AbstractLine2D end" instead.

WARNING: deprecated syntax "abstract AbstractPolygon2D" at /Users/Azamat/.julia/v0.6/GeometricalPredicates/src/GeometricalPredicates.jl:68.
Use "abstract type AbstractPolygon2D end" instead.

WARNING: deprecated syntax "abstract AbstractPrimitive" at /Users/Azamat/.julia/v0.6/GeometricalPredicates/src/GeometricalPredicates.jl:70.
Use "abstract type AbstractPrimitive end" instead.

WARNING: deprecated syntax "abstract AbstractUnOrientedPrimitive<:AbstractPrimitive" at /Users/Azamat/.julia/v0.6/GeometricalPredicates/src/GeometricalPredicates.jl:71.
Use "abstract type AbstractUnOrientedPrimitive<:AbstractPrimitive end" instead.

WARNING: deprecated syntax "abstract AbstractOrientedPrimitive<:AbstractPrimitive" at /Users/Azamat/.julia/v0.6/GeometricalPredicates/src/GeometricalPredicates.jl:72.
Use "abstract type AbstractOrientedPrimitive<:AbstractPrimitive end" instead.

WARNING: deprecated syntax "abstract AbstractPositivelyOrientedPrimitive<:AbstractOrientedPrimitive" at /Users/Azamat/.julia/v0.6/GeometricalPredicates/src/GeometricalPredicates.jl:73.
Use "abstract type AbstractPositivelyOrientedPrimitive<:AbstractOrientedPrimitive end" instead.

WARNING: deprecated syntax "abstract AbstractNegativelyOrientedPrimitive<:AbstractOrientedPrimitive" at /Users/Azamat/.julia/v0.6/GeometricalPredicates/src/GeometricalPredicates.jl:74.
Use "abstract type AbstractNegativelyOrientedPrimitive<:AbstractOrientedPrimitive end" instead.

WARNING: deprecated syntax "abstract AbstractTriangleUnOriented<:AbstractUnOrientedPrimitive" at /Users/Azamat/.julia/v0.6/GeometricalPredicates/src/GeometricalPredicates.jl:76.
Use "abstract type AbstractTriangleUnOriented<:AbstractUnOrientedPrimitive end" instead.

WARNING: deprecated syntax "abstract AbstractTetrahedronUnOriented<:AbstractUnOrientedPrimitive" at /Users/Azamat/.julia/v0.6/GeometricalPredicates/src/GeometricalPredicates.jl:77.
Use "abstract type AbstractTetrahedronUnOriented<:AbstractUnOrientedPrimitive end" instead.

WARNING: deprecated syntax "abstract AbstractPositivelyOrientedTriangle<:AbstractPositivelyOrientedPrimitive" at /Users/Azamat/.julia/v0.6/GeometricalPredicates/src/GeometricalPredicates.jl:78.
Use "abstract type AbstractPositivelyOrientedTriangle<:AbstractPositivelyOrientedPrimitive end" instead.

WARNING: deprecated syntax "abstract AbstractNegativelyOrientedTriangle<:AbstractNegativelyOrientedPrimitive" at /Users/Azamat/.julia/v0.6/GeometricalPredicates/src/GeometricalPredicates.jl:79.
Use "abstract type AbstractNegativelyOrientedTriangle<:AbstractNegativelyOrientedPrimitive end" instead.

WARNING: deprecated syntax "abstract AbstractPositivelyOrientedTetrahedron<:AbstractPositivelyOrientedPrimitive" at /Users/Azamat/.julia/v0.6/GeometricalPredicates/src/GeometricalPredicates.jl:80.
Use "abstract type AbstractPositivelyOrientedTetrahedron<:AbstractPositivelyOrientedPrimitive end" instead.

WARNING: deprecated syntax "abstract AbstractNegativelyOrientedTetrahedron<:AbstractNegativelyOrientedPrimitive" at /Users/Azamat/.julia/v0.6/GeometricalPredicates/src/GeometricalPredicates.jl:81.
Use "abstract type AbstractNegativelyOrientedTetrahedron<:AbstractNegativelyOrientedPrimitive end" instead.

WARNING: deprecated syntax "typealias TriangleTypes Union{AbstractTriangleUnOriented,AbstractPositivelyOrientedTriangle,AbstractNegativelyOrientedTriangle}" at /Users/Azamat/.julia/v0.6/GeometricalPredicates/src/GeometricalPredicates.jl:83.
Use "const TriangleTypes = Union{AbstractTriangleUnOriented,AbstractPositivelyOrientedTriangle,AbstractNegativelyOrientedTriangle}" instead.

WARNING: deprecated syntax "typealias TetrahedronTypes Union{AbstractTetrahedronUnOriented,AbstractPositivelyOrientedTetrahedron,AbstractNegativelyOrientedTetrahedron}" at /Users/Azamat/.julia/v0.6/GeometricalPredicates/src/GeometricalPredicates.jl:84.
Use "const TetrahedronTypes = Union{AbstractTetrahedronUnOriented,AbstractPositivelyOrientedTetrahedron,AbstractNegativelyOrientedTetrahedron}" instead.

WARNING: deprecated syntax "abstract AbstractOrientation" at /Users/Azamat/.julia/v0.6/GeometricalPredicates/src/GeometricalPredicates.jl:224.
Use "abstract type AbstractOrientation end" instead.

WARNING: deprecated syntax "abstract AbstractCoordinate" at /Users/Azamat/.julia/v0.6/GeometricalPredicates/src/GeometricalPredicates.jl:1053.
Use "abstract type AbstractCoordinate end" instead.

WARNING: deprecated syntax "abstract AbstractDirection" at /Users/Azamat/.julia/v0.6/GeometricalPredicates/src/GeometricalPredicates.jl:1069.
Use "abstract type AbstractDirection end" instead.

WARNING: deprecated syntax "inner constructor Line2D(...) around /Users/Azamat/.julia/v0.6/GeometricalPredicates/src/GeometricalPredicates.jl:118".
Use "Line2D{T}(...) where T" instead.

WARNING: deprecated syntax "inner constructor Polygon2D(...) around /Users/Azamat/.julia/v0.6/GeometricalPredicates/src/GeometricalPredicates.jl:171".
Use "Polygon2D{T}(...) where T" instead.

WARNING: deprecated syntax "inner constructor UnOrientedTriangle(...) around none:9".
Use "UnOrientedTriangle{T}(...) where T" instead.

WARNING: deprecated syntax "inner constructor PositivelyOrientedTriangle(...) around none:9".
Use "PositivelyOrientedTriangle{T}(...) where T" instead.

WARNING: deprecated syntax "inner constructor NegativelyOrientedTriangle(...) around none:9".
Use "NegativelyOrientedTriangle{T}(...) where T" instead.

WARNING: deprecated syntax "inner constructor UnOrientedTetrahedron(...) around none:10".
Use "UnOrientedTetrahedron{T}(...) where T" instead.

WARNING: deprecated syntax "inner constructor PositivelyOrientedTetrahedron(...) around none:10".
Use "PositivelyOrientedTetrahedron{T}(...) where T" instead.

WARNING: deprecated syntax "inner constructor NegativelyOrientedTetrahedron(...) around none:10".
Use "NegativelyOrientedTetrahedron{T}(...) where T" instead.
WARNING: Array{T, N}(::Type{T}, d::NTuple{N, Int}) is deprecated, use Array{T}(d) instead.
Stacktrace:
 [1] depwarn(::String, ::Symbol) at ./deprecated.jl:70
 [2] Array(::Type{Int64}, ::Tuple{Int64,Int64}) at ./deprecated.jl:57
 [3] include_from_node1(::String) at ./loading.jl:569
 [4] include(::String) at ./sysimg.jl:14
 [5] anonymous at ./<missing>:2
 [6] eval(::Module, ::Any) at ./boot.jl:235
 [7] process_options(::Base.JLOptions) at ./client.jl:286
 [8] _start() at ./client.jl:371
while loading /Users/Azamat/.julia/v0.6/GeometricalPredicates/src/GeometricalPredicates.jl, in expression starting on line 984
WARNING: Array{T, N}(::Type{T}, d::NTuple{N, Int}) is deprecated, use Array{T}(d) instead.
Stacktrace:
 [1] depwarn(::String, ::Symbol) at ./deprecated.jl:70
 [2] Array(::Type{Int64}, ::Tuple{Int64,Int64}) at ./deprecated.jl:57
 [3] include_from_node1(::String) at ./loading.jl:569
 [4] include(::String) at ./sysimg.jl:14
 [5] anonymous at ./<missing>:2
 [6] eval(::Module, ::Any) at ./boot.jl:235
 [7] process_options(::Base.JLOptions) at ./client.jl:286
 [8] _start() at ./client.jl:371
while loading /Users/Azamat/.julia/v0.6/GeometricalPredicates/src/GeometricalPredicates.jl, in expression starting on line 985
WARNING: Array{T, N}(::Type{T}, d::NTuple{N, Int}) is deprecated, use Array{T}(d) instead.
Stacktrace:
 [1] depwarn(::String, ::Symbol) at ./deprecated.jl:70
 [2] Array(::Type{Int64}, ::Tuple{Int64,Int64}) at ./deprecated.jl:57
 [3] include_from_node1(::String) at ./loading.jl:569
 [4] include(::String) at ./sysimg.jl:14
 [5] anonymous at ./<missing>:2
 [6] eval(::Module, ::Any) at ./boot.jl:235
 [7] process_options(::Base.JLOptions) at ./client.jl:286
 [8] _start() at ./client.jl:371
while loading /Users/Azamat/.julia/v0.6/GeometricalPredicates/src/GeometricalPredicates.jl, in expression starting on line 986
```

### PR DESCRIPTION
**Pull request by juliohm**
Could you please merge this, these warnings can be distracting while debugging upstream packages.

### CODE REVIEW

**Comment by juliohm** [comment]
Is it a good moment to drop support for old Julia versions? The syntax has changed a lot and many packages have dropped support already.

**Comment by juliohm** [comment]
@skariel @robertdj could you please merge this?

**Comment by skariel** [comment]
thanks, done!

**Comment by juliohm** [comment]
Thank you @skariel, should we release a new tag?

**Pull request merged**
